# Generated by Django 3.1.1 on 2020-09-25 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codCliente', models.AutoField(db_column='codCliente', primary_key=True, serialize=False)),
                ('nroRuc', models.CharField(max_length=20)),
                ('vigente', models.CharField(default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codEmple', models.AutoField(primary_key=True, serialize=False)),
                ('direcc', models.CharField(max_length=100)),
                ('hobby', models.CharField(max_length=2000)),
                ('fecNac', models.DateField()),
                ('dni', models.CharField(max_length=20)),
                ('nroCIP', models.CharField(max_length=10)),
                ('fecCIPVig', models.DateField()),
                ('licCond', models.CharField(default='1', max_length=1)),
                ('observac', models.CharField(max_length=300)),
                ('vigente', models.CharField(default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('codPersona', models.AutoField(primary_key=True, serialize=False)),
                ('tipPersona', models.CharField(max_length=1)),
                ('desPersona', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('codPyto', models.AutoField(primary_key=True, serialize=False)),
                ('codSNIP', models.CharField(max_length=10)),
                ('fecReg', models.DateField()),
                ('codFase', models.IntegerField()),
                ('codNivel', models.IntegerField()),
                ('codFuncion', models.CharField(max_length=4)),
                ('codSituacion', models.IntegerField()),
                ('numInfor', models.IntegerField()),
                ('numInforEntrg', models.IntegerField()),
                ('estPyto', models.IntegerField()),
                ('fecEstado', models.DateField()),
                ('nomPyto', models.CharField(max_length=1000)),
                ('valRefer', models.DecimalField(decimal_places=12, max_digits=14)),
                ('costoTotal', models.DecimalField(decimal_places=12, max_digits=14)),
                ('costDirecto', models.DecimalField(decimal_places=12, max_digits=14)),
                ('costGGen', models.DecimalField(decimal_places=12, max_digits=14)),
                ('costImp', models.CharField(max_length=100)),
                ('costPenalid', models.CharField(max_length=100)),
                ('codDpto', models.CharField(max_length=2)),
                ('codProv', models.CharField(max_length=2)),
                ('codDist', models.CharField(max_length=2)),
                ('fechViab', models.DateField()),
                ('observac', models.CharField(max_length=500)),
                ('rutaDoc', models.CharField(max_length=300)),
                ('codObjc', models.IntegerField()),
                ('vigente', models.CharField(max_length=1)),
                ('codCliente', models.ForeignKey(db_column='codCliente', on_delete=django.db.models.deletion.CASCADE, to='T.cliente')),
                ('emplJefeProj', models.ForeignKey(db_column='emplJefeProj', on_delete=django.db.models.deletion.CASCADE, to='T.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('codRutaPy', models.AutoField(primary_key=True, serialize=False)),
                ('nroVersion', models.IntegerField(default=1)),
                ('codRuta', models.CharField(max_length=20)),
                ('fechaRegistro', models.DateField()),
                ('denominacionRuta', models.CharField(max_length=100)),
                ('denominacionCortoRuta', models.CharField(max_length=100)),
                ('nroKms', models.DecimalField(decimal_places=13, max_digits=18)),
                ('zonaGPS', models.CharField(max_length=25)),
                ('progInicio', models.CharField(max_length=25)),
                ('progFinal', models.CharField(max_length=25)),
                ('latitudInicioRuta', models.CharField(max_length=25)),
                ('latitudFinalRuta', models.CharField(max_length=25)),
                ('longitudInicioRuta', models.CharField(max_length=25)),
                ('longitudFinalRuta', models.CharField(max_length=25)),
                ('altitudInicioRuta', models.CharField(max_length=25)),
                ('altitudFinalRuta', models.CharField(max_length=25)),
                ('observacionRuta', models.CharField(max_length=500)),
                ('vigencia', models.CharField(max_length=1)),
                ('codPyto', models.ForeignKey(db_column='codPyto', on_delete=django.db.models.deletion.CASCADE, to='T.proyecto')),
                ('elaboradorPor', models.ForeignKey(db_column='elaboradorPor', on_delete=django.db.models.deletion.CASCADE, to='T.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Tramo',
            fields=[
                ('codTramoPy', models.AutoField(primary_key=True, serialize=False)),
                ('nroVersion', models.IntegerField(default=1)),
                ('codTramo', models.CharField(max_length=20)),
                ('fechaRegistro', models.DateField()),
                ('denominacionTramo', models.CharField(max_length=100)),
                ('denominacionCortoTramo', models.CharField(max_length=100)),
                ('nroKmsTramo', models.DecimalField(decimal_places=13, max_digits=18)),
                ('zonaGPS', models.CharField(max_length=25)),
                ('progInicio', models.CharField(max_length=25)),
                ('progFin', models.CharField(max_length=25)),
                ('latitudInicioTramo', models.CharField(max_length=25)),
                ('latitudFinalTramo', models.CharField(max_length=25)),
                ('longitudInicioTramo', models.CharField(max_length=25)),
                ('longitudFinalTramo', models.CharField(max_length=25)),
                ('altitudInicioTramo', models.CharField(max_length=25)),
                ('altitudFinalTramo', models.CharField(max_length=25)),
                ('observacionTramo', models.CharField(max_length=500)),
                ('vigencia', models.CharField(max_length=1)),
                ('codPyto', models.ForeignKey(db_column='codPyto', on_delete=django.db.models.deletion.CASCADE, to='T.proyecto')),
                ('codRutaPy', models.ForeignKey(db_column='codRutaPy', on_delete=django.db.models.deletion.CASCADE, to='T.ruta')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='codPersona',
            field=models.OneToOneField(db_column='codPersona', on_delete=django.db.models.deletion.CASCADE, to='T.persona'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codPersona',
            field=models.OneToOneField(db_column='codPersona', on_delete=django.db.models.deletion.CASCADE, to='T.persona'),
        ),
    ]
