# Generated by Django 3.1.1 on 2020-09-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codCliente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='ruta',
            unique_together={('codPyto', 'codRutaPy', 'nroVersion')},
        ),
        migrations.AlterUniqueTogether(
            name='tramo',
            unique_together={('codPyto', 'codRutaPy', 'codTramoPy', 'nroVersion')},
        ),
    ]
