# Generated by Django 3.1.1 on 2020-09-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='costImp',
            field=models.DecimalField(decimal_places=12, max_digits=14),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='costPenalid',
            field=models.DecimalField(decimal_places=12, max_digits=14),
        ),
    ]
