# Generated by Django 3.1.1 on 2020-09-21 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T', '0002_auto_20200921_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='codPyto',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(6)]),
        ),
    ]
