# Generated by Django 3.1.1 on 2020-09-21 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('T', '0003_auto_20200921_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='emplJefeProj',
            field=models.ForeignKey(db_column='emplId', on_delete=django.db.models.deletion.CASCADE, to='T.empleado'),
        ),
    ]
