# Generated by Django 3.1.1 on 2020-09-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T', '0004_auto_20200921_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='codPyto',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
