# Generated by Django 3.1.1 on 2020-09-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T', '0006_auto_20200921_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='codPyto',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estPyto',
            field=models.DecimalField(decimal_places=6, max_digits=6),
        ),
    ]
