# Generated by Django 3.1.1 on 2020-09-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T', '0007_auto_20200921_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('codPrueba', models.DecimalField(decimal_places=6, max_digits=6, primary_key=True, serialize=False)),
                ('emplJefeProj', models.CharField(max_length=20)),
                ('valRefer', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
    ]
