# Generated by Django 3.1.1 on 2020-09-22 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('T', '0008_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='emplJefeProj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='T.empleado'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estPyto',
            field=models.IntegerField(),
        ),
    ]
